project:
    title: CTIS
    description: Crypto Trading Information System
    version: 1.0.0
    authors:
        - name: John Doe
          email:
        - name: Jane Doe
          email:
        - name: John Smith
          email:
        - name: Jane Smith
          email:
    license: MIT
