project:
    title: CTIS
    description: Crypto Trading Information System
    version: 1.0.0
    authors:
        - name: Arda Becanım
        - name: Kerem Coşkun
        - name: Oktay Giniş
        - name: Sezer Tetik
    license: MIT
